### ISSUE TITLE
Two odd functionalities on running PyStone

### ISSUE THREAD

**Issue by Boeing737ng** [pybee/batavia#687] opened 2017-11-13 13:40 UTC
Hi, I was going through its features and just playing around with it before i start contributing this project. While doing so, I found something odd while i was running PyStone on my local environment. 

Firstly, it appears to give a result of 50000 loops regardless of which loops we choose to run.
Secondly, it takes too long time (more than 100 sec) to run PyStone when it takes less than a second on my terminal.

By the way, I'm using Python 3.5 and Mac OS with High Sierra 10.13.1

**Comment by freakboy3742** [comment] 2017-11-21 08:10
Looks like a duplicate of #602

**Closed by freakboy3742** 2017-11-21 08:10 UTC
Labels: duplicate
