### ISSUE TITLE
handle key word args for str.__mod__

### ISSUE THREAD

**Issue by jstoebel** [pybee/batavia#412] opened 2017-01-27 15:17 UTC
`str.__mod__` has been partially implemented (old string formatting) but can't yet accept key word arguments. I will get started on this.

**Comment by freakboy3742** [comment] 2017-03-19 02:14
I'm going to close this as a duplicate of #46 - there's no need to document each individual unimplemented feature.

**Closed by freakboy3742** 2017-03-19 02:14 UTC
Labels: duplicate
